version: '3.1'
services:
    mysql:
        image: 'mariadb:11'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=server
            - MYSQL_USER=joomla
            - MYSQL_PASSWORD=password
        ports:
            - '21002:3306'

    redis:
      image: redis
      ports:
       - "21003:6379"

    php:
        build:
            context: .
        entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
        ports:
            - '21001:8000'
        volumes:
            - .:/app
