services:
    mysql:
        image: 'mariadb:11'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=server
            - MYSQL_USER=joomla
            - MYSQL_PASSWORD=password
        ports:
            - '21002:3306'
        volumes:
            - joomla-autoupdates-mariadb:/var/lib/mysql

    redis:
      image: redis
      ports:
       - "21003:6379"

    php:
        build:
            context: .
            args:
                UID: ${HOST_UID}
                GID: ${HOST_GID}
        entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
        ports:
            - '21001:8000'

volumes:
  joomla-autoupdates-mariadb:
